namespace: kore
packages: docker.pkg.github.com/rxsto/kore/
secret: kore-github-packages
api:
  name: api
  replicas: 3
  config: api-config
  image:
    name: api
    tag: :latest
  port: 5000
  probes:
    liveness: /actuator/health/liveness
    readiness: /actuator/health/readiness
