api:
  name: api
  namespace: api
  port: 5000
  replicaCount: 3
  image:
    group: docker.pkg.github.com
    name: api
    tag: latest
  configMap: api-config
  probes:
    liveness: /actuator/health/liveness
    readiness: /actuator/health/readiness
