namespace: kore-staging
packages: docker.pkg.github.com/rxsto/
secret: kore-staging-github-packages
api:
  name: api-staging
  replicas: 3
  config: api-staging-config
  image:
    name: api
    tag: :latest
  port: 5000
  probes:
    liveness: /actuator/health/liveness
    readiness: /actuator/health/readiness
