namespace: rxsto
packages: gcr.io/rxs-to/
secret: rxsto-gcr
api:
  name: kore-api
  replicas: 3
  config: kore-api-config
  image:
    name: kore-api
    tag: :latest
  port: 5000
    host: api.rxs.to
    path: /
  probes:
    liveness: /actuator/health/liveness
    readiness: /actuator/health/readiness
