namespace: rxsto
packages: ghcr.io/rxsto/kore-api
secret: kore-ghcr
api:
  name: kore-api
  replicas: 3
  config: kore-api-config
  image:
    name: kore-api
    tag: :latest
  port: 5000
  probes:
    liveness: /actuator/health/liveness
    readiness: /actuator/health/readiness
