namespace: rxsto-staging
packages: gcr.io/rxs-to/
secret: rxsto-staging-gcr
api:
  name: kore-api-staging
  replicas: 3
  config: kore-api-staging-config
  image:
    name: kore-api
    tag: :latest
  port: 5000
  probes:
    liveness: /actuator/health/liveness
    readiness: /actuator/health/readiness
