api:
  name: api-staging
  namespace: api-staging
  port: 5000
  replicaCount: 3
  image:
    group: docker.pkg.github.com/rxsto/
    name: api
    tag: :latest
  configMap: api-staging-config
  probes:
    liveness: /actuator/health/liveness
    readiness: /actuator/health/readiness
