apiVersion: v1
kind: Service
metadata:
  name: { { .Values.api.name } }
  namespace: { { .Values.api.namespace } }
  labels:
    app: { { .Values.api.name } }
spec:
  selector:
    app: { { .Values.api.name } }
  ports:
    - protocol: TCP
      port: { { .Values.api.port } }
      targetPort: { { .Values.api.port } }
