version: v1.0
name: Staging Deploy Pipeline

agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: Deploy to Kubernetes Cluster
    task:
      secrets:
        - name: kubeconfig
        - name: helmvalues
      env_vars:
        - name: KUBECONFIG
          value: /home/semaphore/.kube/config
        - name: HELMVALUES
          value: /home/semaphore/kore/api.yaml
        - name: RELEASE_NAME
          value: api
        - name: NAMESPACE
          value: api
      jobs:
        - name: Execute Helm Upgrade
          commands:
            - rm -rf ./kore/
            - checkout
            - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
            - helm upgrade -i $RELEASE_NAME ./chart
              --set image.tag=${SEMAPHORE_GIT_SHA}
              --namespace $NAMESPACE
              --values $HELMVALUES
